# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name_client',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
