# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_auto_20170406_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name_client',
            field=models.CharField(max_length=20),
        ),
    ]
